[tool.black]
exclude = '''
(
  /(
      \.git
    | \.mypy_cache
    | \.venv
    | migrations
    | build
    | dist
  )/
)
'''
line-length = 79
skip-string-normalization = true

[tool.mypy]
exclude = '''
/(
    \.idea
  | \.git
  | \.DS_Store
  | \.vscode
  | \.venv
)/
'''
ignore_missing_imports = true
verbose = true