# Generated by Django 3.2.16 on 2023-02-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'categories', 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'default_related_name': 'items', 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AddField(
            model_name='category',
            name='formatted_name',
            field=models.CharField(editable=False, max_length=150, null=True, verbose_name='форматированное имя'),
        ),
        migrations.AddField(
            model_name='tag',
            name='formatted_name',
            field=models.CharField(editable=False, max_length=150, null=True, verbose_name='форматированное имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, null=True, verbose_name='название'),
        ),
    ]
