# Generated by Django 3.2.16 on 2023-02-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_galleryimage_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainimage',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.mainimage'),
        ),
    ]
