# Generated by Django 3.2.16 on 2023-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20230226_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(null=True, upload_to='catalog/', verbose_name='Будет приведено к ширине 300x300'),
        ),
    ]
