# Generated by Django 3.2.16 on 2023-02-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_item_main_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainImage',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='main_image',
            new_name='image',
        ),
    ]
