# Generated by Django 3.2.16 on 2023-03-01 14:24

import catalog.validators
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20230226_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Описание должно содержать слова "превосходно" или "роскошно"', null=True, validators=[catalog.validators.ValidateMustContain('роскошно', 'превосходно')], verbose_name='описание'),
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='catalog/', verbose_name='Главное изображение')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item')),
            ],
            options={
                'verbose_name': 'главное изображение',
                'default_related_name': 'main_image',
            },
        ),
    ]
