# Generated by Django 3.2.16 on 2023-03-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20230301_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='на главной'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item'),
        ),
    ]
