# Generated by Django 3.2.16 on 2023-03-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
        ('catalog', '0010_auto_20230312_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='rating.Rating', verbose_name='Оценка'),
        ),
    ]
