# Generated by Django 3.2.16 on 2023-03-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_rating_rating'),
        ('catalog', '0011_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='items', to='rating.Rating', verbose_name='Оценка'),
        ),
    ]
