# Generated by Django 3.2.16 on 2023-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_item_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/', verbose_name='галерея'),
        ),
    ]
