# Generated by Django 3.2.16 on 2023-03-12 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='содержание письма', verbose_name='содержание письма')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, help_text='время создания письма', verbose_name='время создания')),
                ('email', models.EmailField(help_text='почта', max_length=254, verbose_name='почта')),
            ],
        ),
    ]
