# Generated by Django 3.2.16 on 2023-03-26 18:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_normalized_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Аватарка', null=True, upload_to=users.models.UserProfile.get_image_filename, verbose_name='аватарка'),
        ),
    ]
